# Generated by Django 4.0.2 on 2022-02-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=10, unique=True, verbose_name='Phone no (+91)'),
        ),
    ]
