# Generated by Django 4.0.2 on 2022-02-19 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_color_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='estimated_price',
            new_name='price_per_metre',
        ),
        migrations.CreateModel(
            name='AvailableMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('cid', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to='shop.color')),
                ('mid', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to='shop.material')),
            ],
            options={
                'ordering': ['available_length'],
            },
        ),
        migrations.AddConstraint(
            model_name='availablematerial',
            constraint=models.UniqueConstraint(fields=('mid', 'cid'), name='AvailableMaterialConstraint'),
        ),
    ]
