# Generated by Django 4.0.2 on 2022-02-19 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_estimated_price_material_price_per_metre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablematerial',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.color'),
        ),
        migrations.AlterField(
            model_name='availablematerial',
            name='mid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.material'),
        ),
        migrations.AlterField(
            model_name='color',
            name='value',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
