# Generated by Django 4.0.2 on 2022-02-19 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_availablematerial_cid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sample_url',
            field=models.URLField(default='https://images.unsplash.com/photo-1618932260643-eee4a2f652a6?w=300', max_length=300),
        ),
        migrations.AlterField(
            model_name='availablematerial',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.color', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='availablematerial',
            name='mid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.material', verbose_name='Material'),
        ),
    ]
