# Generated by Django 4.0.2 on 2022-02-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_item_sample_url_alter_availablematerial_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablematerial',
            name='available_length',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Available length (in meters)'),
        ),
    ]
