# Generated by Django 4.0.2 on 2022-02-20 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_of_delivery',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Deliver by'),
            preserve_default=False,
        ),
    ]
