# Generated by Django 4.0.2 on 2022-02-20 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_order_date_of_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('works_on', models.ManyToManyField(null=True, through='shop.AssignedWork', to='shop.Order')),
            ],
        ),
        migrations.AddField(
            model_name='assignedwork',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.employee'),
        ),
        migrations.AddField(
            model_name='assignedwork',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='worked_on_by',
            field=models.ManyToManyField(through='shop.AssignedWork', to='shop.Employee'),
        ),
    ]
