# Generated by Django 4.0.2 on 2022-02-20 15:28

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_account_alter_employee_works_on_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_of_delivery',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2022, 2, 20))], verbose_name='Deliver by'),
        ),
    ]
